<script setup>
import {defaultResponse} from './default-response.js'
import {ref,computed,onMounted,onBeforeUnmount,watch} from 'vue'
import DirectoryPicker from './DirectoryPicker.vue'
import ConfigPanel from './ConfigPanel.vue'
import {modes,validateGroupConfiguration} from './group-configuration.js'
const props=defineProps({group:Object,request:Function,project:String,creating:Boolean,virtualAgent:Boolean,inline:Boolean})
const emit=defineEmits(['close','saved'])
const draft=ref(null),version=ref(0),baseline=ref(''),section=ref('members'),error=ref(''),notice=ref(''),busy=ref(false),path=ref(''),role=ref('')
function reset(group){draft.value={name:group.body.name,role:group.body.role||'',response_instructions:group.body.response_instructions??defaultResponse,workspace:{workdir:group.body.workspace?.workdir||'',outside_access:group.body.workspace?.outside_access||''},policy:JSON.parse(JSON.stringify(group.body.policy))};draft.value.policy.relay_strategy??='manual';version.value=group.version;baseline.value=JSON.stringify(draft.value);error.value=''}
reset(props.group)
if(props.creating)section.value=props.virtualAgent?'general':'members'
const candidates=ref([]),retained=ref(''),switchingToChat=ref(false)
const memberLimit=computed(()=>draft.value.policy.mode==='chat'?1:8)
function chooseMode(mode){if(mode==='chat'&&draft.value.policy.members.length>1){switchingToChat.value=true;retained.value='';return}draft.value.policy.mode=mode;switchingToChat.value=false;if(mode==='chat'){draft.value.policy.leader=null;draft.value.policy.rounds=1}}
function confirmChat(){if(!retained.value)return;draft.value.policy.members=draft.value.policy.members.filter(m=>m.path.join('/')===retained.value);chooseMode('chat')}
const statusLoading=ref(false),statusError=ref('')
let statusTimer,alive=true
async function refreshStatus(){
 if(statusLoading.value)return
 statusLoading.value=true
 try{const result=await props.request('/v1/repl/'+props.project+'/agents/candidates');if(alive){if(JSON.stringify(candidates.value)!==JSON.stringify(result.agents))candidates.value=result.agents;statusError.value=''}}
 catch(e){if(alive)statusError.value=e.message}
 finally{statusLoading.value=false}
}
function memberStatus(member){const agent=candidates.value.find(a=>a.id===member.path.join('/'));if(statusError.value||!agent)return {label:'未知',type:'warning'};return agent.kind==='virtual'?{label:'已配置',type:'info'}:agent.online?{label:'在线',type:'success'}:{label:'离线',type:'info'}}
onMounted(()=>{refreshStatus();statusTimer=setInterval(()=>{if(!document.hidden)refreshStatus()},5000)})
onBeforeUnmount(()=>{alive=false;clearInterval(statusTimer)})
const selectedMode=computed(()=>modes.find(m=>m.id===draft.value.policy.mode))
watch(path,id=>{const agent=candidates.value.find(a=>a.id===id);role.value=agent?.role||''})
const dirty=computed(()=>JSON.stringify(draft.value)!==baseline.value)
const leader=computed({get:()=>draft.value.policy.leader?.join('/')||'',set:value=>draft.value.policy.leader=value?value.split('/'):null})
function add(){if(draft.value.policy.members.length>=memberLimit.value){error.value='当前模式最多 '+memberLimit.value+' 个成员。';return}const value=path.value.trim();if(!candidates.value.some(a=>a.id===value)){error.value='请从已配置 Agent 或已连接 Crabot 中选择。';return}const next=JSON.parse(JSON.stringify(draft.value));next.policy.members.push({path:value.split('/'),role:role.value.trim()||'member'});const invalid=validateGroupConfiguration({...next,name:next.name||'新项目',policy:{...next.policy,mode:'relay'}});if(invalid){error.value=invalid;return}draft.value=next;path.value='';role.value='';error.value=''}
function remove(index){const [member]=draft.value.policy.members.splice(index,1);if(member.path.join('/')===leader.value)leader.value=''}
function move(index,direction){const members=draft.value.policy.members;[members[index],members[index+direction]]=[members[index+direction],members[index]]}
async function save(){error.value=props.virtualAgent&&!draft.value.name.trim()?'请填写虚拟 Agent 名称。':validateGroupConfiguration(draft.value);if(error.value)return;busy.value=true;notice.value='';try{const updated=await props.request((props.virtualAgent?`/v1/repl/${props.project}/virtual-agents`:props.creating?`/v1/repl/${props.project}/groups`:`/v1/repl/${props.project}/groups/${props.group.key}/configuration`),{method:props.creating?'POST':'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...draft.value,workspace:props.virtualAgent?undefined:{workdir:draft.value.workspace.workdir.trim()||null,outside_access:draft.value.workspace.outside_access||null},id:props.virtualAgent&&props.group.key?props.group.key:undefined,expected_version:version.value})});reset(updated);notice.value='项目配置已保存，后续轮次使用新策略。';emit('saved',updated);if(!props.creating)emit('close')}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template>
 <ConfigPanel :inline="inline" :title="virtualAgent?'虚拟 Agent 配置':creating?'创建项目':'项目配置'" eyebrow="COLLABORATION SETTINGS" :description="virtualAgent?'将一组 Agent 组合成一个对外能力；名称必填，策略可复用。':creating?'选择成员与协作策略；项目名称可留空，首次发送消息后自动生成。':group.body.name+' · 策略版本 v'+version" :busy="busy" :dirty="dirty" @close="emit('close')">
  <div class="config-split group-config-layout"><nav class="config-nav"><span class="nav-caption">配置项目</span><el-button type="primary" native-type="button" :class="{active:section==='members'}" @click="section='members'">♧ 成员与角色<small>角色默认带入，可按项目调整</small></el-button><el-button type="primary" native-type="button" :class="{active:section==='strategy'}" @click="section='strategy'">◎ 协作策略<small>模式、Leader、轮次</small></el-button><el-button type="primary" native-type="button" v-if="!virtualAgent" :class="{active:section==='workspace'}" @click="section='workspace'">⌂ 工作目录<small>运行位置与目录访问权限</small></el-button><el-button type="primary" native-type="button" :class="{active:section==='general'}" @click="section='general'">⚙ 基本信息<small>项目名称与标识</small></el-button><div class="nav-note">配置属于当前项目。已有执行保留原策略，保存不会打断正在进行的任务。</div></nav>
  <div class="config-detail">
   <div v-if="!creating&&group.version!==version" class="config-alert warning">远端配置已更新，你的草稿不会被覆盖。<el-button type="default" native-type="button" class="secondary" :disabled="busy" @click="reset(group)">放弃草稿，载入最新配置</el-button></div>
   <div v-if="error" class="config-alert danger" role="alert">{{error}}</div><div v-if="notice" class="config-alert success" role="status">{{notice}}</div>
   <fieldset :disabled="busy" class="config-fields">
    <template v-if="section==='strategy'"><div class="section-heading"><h3>如何让 Agent 协作</h3><p>为这个项目选择交流机制，再定义共同目标。</p></div><el-radio-group class="mode-options" :model-value="draft.policy.mode" @change="chooseMode"><el-radio-button v-for="mode in modes.filter(m=>!virtualAgent||m.id!=='chat')" :key="mode.id" :value="mode.id">{{mode.name}}</el-radio-button></el-radio-group><p class="mode-explanation">{{selectedMode?.description}}</p>
    <div v-if="switchingToChat" class="config-alert warning"><p>简单聊天只能保留一个 Agent，请选择。其余成员仅从本项目移除，不删除 Agent 配置。</p><el-select v-model="retained" aria-label="简单聊天保留成员"><el-option value="" :label="&quot;选择要保留的 Agent&quot;" /><el-option v-for="m in draft.policy.members" :key="m.path.join('/')" :value="m.path.join('/')" :label="(m.path.join('/'))" /></el-select><el-button type="primary" native-type="button" :disabled="!retained" @click="confirmChat">确认切换</el-button><el-button type="default" native-type="button" class="secondary" @click="switchingToChat=false">取消</el-button></div>
    <div v-if="draft.policy.mode!=='chat'" class="form-card form-grid"><label v-if="draft.policy.mode==='pmo'">Leader<el-select v-model="leader" aria-label="群 Leader"><el-option value="" :label="&quot;选择一个成员&quot;" /><el-option v-for="member in draft.policy.members" :key="member.path.join('/')" :value="member.path.join('/')" :label="(member.path.join('/'))+&quot; · &quot;+(member.role)" /></el-select><small>负责制定计划、分配任务与汇总结果。</small></label><label v-if="draft.policy.mode==='a2a'">最多讨论轮次<el-input-number :min="1" :max="60" :step="1" v-model="draft.policy.rounds" aria-label="最多讨论轮次" /><small>无关成员让出；有结论且其他成员确认或让出后结束。全部让出则提示无人认领，最多 60 轮。</small></label><label v-if="draft.policy.mode==='relay'">接力顺序<el-select v-model="draft.policy.relay_strategy" aria-label="接力策略"><el-option value="manual" :label="&quot;手动指定优先级&quot;" /><el-option value="random" :label="&quot;每次任务随机排列&quot;" /><el-option value="negotiated" :label="&quot;Agent 协商接手意愿&quot;" /></el-select><small v-if="draft.policy.relay_strategy==='manual'">在「成员与角色」中上移/下移，排在前面的优先。</small><small v-else-if="draft.policy.relay_strategy==='random'">任务开始时随机排序，本次接力期间保持不变。</small><small v-else>每位成员自报接手意愿，分数高的优先；平分按手动顺序。协商最多增加每个成员一次调用；超时或无效响应随机分配 0–100 优先级。</small></label></div>
    <label class="field-stack">协作要求<el-input type="textarea" v-model="draft.policy.instructions" rows="5" placeholder="例如：先确认需求，再执行；结论应标明依据与待确认事项。" aria-label="协作要求"></el-input><small>将作为整个项目的共同指令，最多 8192 字节。</small></label></template>
    <template v-if="section==='members'"><div class="section-heading"><h3>成员与角色 <span class="count-pill">{{draft.policy.members.length}} / {{memberLimit}}</span></h3><p>顺序影响接力优先级及 讨论发言次序。调整后统一保存。</p><el-button text :loading="statusLoading" @click="refreshStatus">刷新状态</el-button><small v-if="statusError" role="alert">状态暂不可用：{{statusError}}</small></div><el-table :data="draft.policy.members" class="member-table" row-key="path" empty-text="先选择一个 Agent，添加到项目" style="width:100%">
<el-table-column label="Agent" min-width="180"><template #default="{row,$index}"><span class="number-pill">{{$index+1}}</span><code>{{row.path.join('/')}}</code><el-tag v-if="leader===row.path.join('/')" size="small">Leader</el-tag></template></el-table-column>
<el-table-column label="状态" width="85"><template #default="{row}"><el-tag size="small" :type="memberStatus(row).type">{{memberStatus(row).label}}</el-tag></template></el-table-column>
<el-table-column label="成员职责" min-width="200"><template #default="{row}"><el-input v-model="row.role" :aria-label="row.path.join('/')+' 角色'" placeholder="角色或职责"/></template></el-table-column>
<el-table-column label="操作" width="145"><template #default="{$index}"><div class="row-actions"><el-button text :disabled="$index===0" :aria-label="'上移 '+draft.policy.members[$index].path.join('/')" @click="move($index,-1)">↑</el-button><el-button text :disabled="$index===draft.policy.members.length-1" :aria-label="'下移 '+draft.policy.members[$index].path.join('/')" @click="move($index,1)">↓</el-button><el-button text type="danger" @click="remove($index)">移除</el-button></div></template></el-table-column></el-table><div class="form-card"><h4>选择项目成员</h4><div class="inline-form"><label>选择 Agent<el-select v-model="path" aria-label="选择项目 Agent"><el-option value="" :label="&quot;请选择已配置的 Agent&quot;" /><el-option v-for="a in candidates.filter(a=>(!virtualAgent||a.id!==group.key)&&!draft.policy.members.some(m=>m.path.join('/')===a.id))" :key="a.id" :value="a.id" :label="(a.name||a.id)+&quot; · &quot;+(a.kind==='remote'?'远程 Crabot':a.provider||'虚拟 Agent')+&quot; · &quot;+(a.kind==='virtual'?'已配置':a.online?'在线':'已停止')" /></el-select></label><label>成员职责<el-input v-model="role" placeholder="默认使用 Agent 角色，可在本项目覆盖" /></label><el-button type="primary" native-type="button" :disabled="draft.policy.members.length>=(draft.policy.mode==='chat'?1:8)" @click="add">＋ 添加成员</el-button></div><small>只能选择管理页已配置的 Agent 或已连接的远程 Crabot；停止的 Agent 可加入，但启动后才能执行。</small></div></template>
    <template v-if="section==='workspace'"><div class="section-heading"><h3>工作目录与访问权限</h3><p>本项目的本地 Agent、命令及 Python 使用同一工作目录。远端 Agent 由其所属节点管理，不接收本地目录配置。</p></div><div class="form-card"><label class="field-stack">工作目录<DirectoryPicker v-model="draft.workspace.workdir" :request="request"/><small>选择 Crabot 所在机器的已有目录；留空继承启动目录。</small></label><label class="field-stack">目录外访问<el-select v-model="draft.workspace.outside_access" aria-label="项目目录外访问"><el-option value="" :label="&quot;继承实例设置&quot;" /><el-option value="deny" :label="&quot;禁止访问&quot;" /><el-option value="ask" :label="&quot;每次访问前询问&quot;" /></el-select><small>询问模式需以 --outside-access ask 启动实例；不提供无确认的无限制访问。命令和 CLI 仍受原生沙箱限制。</small></label></div><div class="security-note">保存后用于新任务，正在执行的任务保留原目录配置。只影响本项目，不更改 Agent 默认配置。</div></template>
    <template v-if="section==='general'"><div class="section-heading"><h3>基本信息</h3><p>清晰的名称让项目更容易识别。</p></div><label class="field-stack">{{virtualAgent?'Agent 名称':'项目名称（可选）'}}<el-input v-model="draft.name" aria-label="项目名称"  :placeholder="virtualAgent?'填写虚拟 Agent 名称':'可留空，首次消息后自动命名'" /></label><label v-if="virtualAgent" class="field-stack">角色定义<el-input type="textarea" v-model="draft.role" rows="3" maxlength="255" placeholder="这个虚拟 Agent 对外承担什么职责"></el-input><small>加入项目时自动带入；不填写则使用 Agent 名称。</small></label><label v-if="virtualAgent" class="field-stack">回复要求（提示词）<el-input type="textarea" v-model="draft.response_instructions" :rows="3" maxlength="8192" aria-label="虚拟 Agent 回复要求"/></label><div v-if="!creating" class="form-card metadata-grid"><span>项目标识</span><code>{{group.key}}</code><span>配置版本</span><b>v{{version}}</b></div></template>
   </fieldset>
  </div></div>
  <footer class="config-footer"><span>{{dirty?'● 有未保存的修改':'所有修改已保存'}} · 不影响当前执行</span><div><el-button type="default" native-type="button" class="secondary" :disabled="busy||!dirty" @click="reset(group)">撤销修改</el-button><el-button type="primary" native-type="button" :disabled="busy||!dirty||switchingToChat" @click="save">{{busy?'保存中…':creating?(virtualAgent?'创建虚拟 Agent':'创建项目'):(virtualAgent?'保存虚拟 Agent':'保存项目配置')}}</el-button></div></footer>
 </ConfigPanel>
</template>

<style scoped>
.mode-options{display:flex;flex-wrap:wrap;gap:0}.member-table{margin-bottom:22px}
.mode-card{display:grid;grid-template-columns:30px 1fr;align-items:center;gap:4px 10px;padding:14px 36px 14px 14px}
.mode-card .mode-icon{display:block;grid-row:span 2;font-size:22px;margin:0;color:var(--accent)}
.mode-card b,.mode-card small{margin:0;line-height:1.5}.mode-card input{top:17px;right:12px}
.mode-explanation{font-size:12px;line-height:1.7;color:var(--muted);margin:12px 0 22px;padding-left:12px;border-left:2px solid var(--accent)}
@media(max-width:560px){.mode-grid{grid-template-columns:1fr}}
</style>
