<script setup>
import {ref} from 'vue'
import {peerManagementUrl} from './peer-management.js'
const props=defineProps({request:Function,project:String,mounts:Array,busy:Boolean})
const emit=defineEmits(['pending','changed'])
const confirming=ref(null),deleting=ref(false),notice=ref('')
async function configure(){working.value=true;error.value='';try{await props.request('/v1/repl/'+props.project+'/peers',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({name:confirming.value.name,direction:confirming.value.direction,disabled:deleting.value||!confirming.value.disabled,deleted:deleting.value})});confirming.value=null;emit('changed')}catch(e){error.value=e.message}finally{working.value=false}}
function status(row){return row.status==='failed'?'连接失败':row.disabled?'已断开':row.status==='connected'?'已连接':row.status==='connecting'?'连接中':row.status==='offline'?'离线':'连接失败'}
const url=ref(''),error=ref(''),working=ref(false)
async function connect(){working.value=true;error.value='';try{const result=await props.request('/v1/repl/'+props.project+'/peers/mount',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:url.value})});if(result.status==='pending')emit('pending',result);else{notice.value=result.status==='connected'?'已连接，无需重复连接。':'已有此连接，请在列表中手动重试。';emit('changed')}}catch(e){error.value=e.message}finally{working.value=false}}
</script>
<template>
 <section class="form-card"><h3>连接到上游 Crabot</h3><p class="binding-note">只需填写可达地址。连接标识与 AK/SK 自动生成并保存在本机，无需邀请码。上游创建项目时主动选择本节点提供的 Agent。</p>
  <el-form @submit.prevent="connect" label-position="top"><label class="field-stack">上游地址<el-input v-model="url" type="url" required placeholder="https://crabot.example.com" aria-label="上游地址" /></label><p class="security-note">连接会允许上游发现和调用本节点的 Agent，并保留现有子树管理授权。下一步需要明确确认。跨公网请使用 HTTPS 或可信 VPN。</p><p v-if="notice" class="binding-note">{{notice}}</p><p v-if="error" class="config-alert danger" role="alert">{{error}}</p><div class="editor-actions"><el-button type="primary" native-type="submit" :disabled="working||busy">申请连接</el-button></div></el-form>
 </section>
 <section class="network-list"><h3>已接入网络</h3><p class="binding-note">展示上游与接入下游。连接仅尝试一次，失败或掉线后需手动重试。断开不自动取消已有任务。</p>
 <el-table empty-text="尚未接入其它 Crabot" :data="mounts"  :row-key="row=>row.direction+row.name"><el-table-column label="节点 / 远程地址" min-width="240"><template #default="{row}"><span class="peer-address">{{row.url||row.remote_address||row.node_id||row.name}}</span><small class="peer-id">{{row.name}}</small><small v-if="!row.url" class="peer-id">连接来源地址，非远端 Web 地址</small></template></el-table-column><el-table-column label="方向" width="90"><template #default="{row}">{{row.direction==='downstream'?'下游':'上游'}}</template></el-table-column><el-table-column prop="status" label="状态" width="150"><template #default="{row}"><el-tag :type="row.status==='connected'?'success':'info'">{{status(row)}}</el-tag></template></el-table-column><el-table-column label="操作" width="240" fixed="right"><template #default="{row}"><a v-if="peerManagementUrl(row.url)" class="peer-manage-link" :href="peerManagementUrl(row.url)" target="_blank" rel="noopener noreferrer">打开 Crabot ↗</a><el-button link :type="row.disabled?'primary':'danger'" :disabled="working||busy" @click="deleting=false;confirming=row">{{row.disabled?(row.direction==='upstream'?'重试':'允许接入'):'断开'}}</el-button><el-button link type="danger" :disabled="working||busy" @click="deleting=true;confirming=row">删除</el-button></template></el-table-column></el-table></section>
 <el-dialog :model-value="!!confirming" :title="deleting?'删除连接？':confirming?.disabled?'重试 / 允许接入？':'断开连接？'" width="min(440px,95vw)" append-to-body @close="confirming=null"><p class="peer-address">{{confirming?.url||confirming?.node_id||confirming?.name}}</p><p>{{deleting?'移除连接配置并保持断开，聊天记录保留。':confirming?.disabled?'上游只尝试连接一次；下游解除限制后仍需对方手动重试。':'停止后续通信并保留配置与聊天记录；重启后也保持断开。已有任务可能继续执行。'}}</p><template #footer><el-button @click="confirming=null">取消</el-button><el-button type="primary" :loading="working" @click="configure">确认</el-button></template></el-dialog>
</template>

<style scoped>.peer-manage-link{color:var(--el-color-primary);font-size:12px;margin-right:10px;text-decoration:none}.peer-address{display:block;white-space:normal;overflow-wrap:anywhere;word-break:break-all;line-height:1.6}.peer-id{display:block;color:var(--muted);font-size:11px;overflow-wrap:anywhere}.network-list{min-width:0}</style>
