mod bridge;
mod context;
mod contract;
mod exposure;
mod factory;
mod find;
mod find_depth;
pub use agent_tool_macros::tool;
pub use exposure::{DISCOVERY_TOOLS, ToolIndex};
pub use find_depth::FindDepth;
mod compact;
mod registry;
mod runtime;
pub use context::ToolContext;
pub use contract::{Tool, ToolDefinition, ToolFuture, ToolSession};
pub use factory::{ToolFactory, ToolRegistration};
pub use inventory as registrations;
pub use registry::ToolRegistry;
pub(crate) use runtime::ToolRuntime;
pub use serde_json as json;
mod external_command;
mod policy;
mod shell;
mod shell_execution;
pub use policy::{ExternalCommand, ToolPolicy};
